name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1
        run: echo "This is the first job"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 2
        run: echo "This is the second job"